[package]
authors = ["tgotwig <thomas@tgotwig.dev>"]
edition = "2021"
name = "vidmerger"
version = "0.1.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.0"
clap = {version = "3.0.0-beta.1", features = ["yaml"]}
nanoid = "0.4.0"
path-slash = "0.1.4"
regex = "1"
system_shutdown = "3.0.0"
term-painter = "0.2.4"
which = "4.0.2"
